[parity]
chain = "./chain.spec"

[network]
warp = false

[rpc]
apis = ["web3","eth","net","parity","traces"]
processing_threads = 8
server_threads = 16
interface = "0.0.0.0"
cors=["all"]

[websockets]
port = 8546
interface = "0.0.0.0"
max_connections = 1000
apis = ["web3","eth","net","parity","pubsub","traces"]
origins = ["all"]
hosts = ["all"]

[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"
cache_size_db = 12000